import "server-only";
import { createHash } from "node:crypto";
import type { Lead } from "./lead";

/**
 * Double-send guard.
 *
 * Two things cause the same lead to arrive twice: a visitor double-clicking
 * submit (or hitting it again because the first response was slow), and a
 * client-side retry. Neither should put two notifications in Fred's inbox and
 * two confirmations in the customer's.
 *
 * The guard remembers a fingerprint of every submission that was ACTUALLY
 * delivered, with the reference it was given. A repeat inside the window is
 * treated as already-delivered: nothing is sent, the visitor still sees the
 * success state, and the log line carries the original reference so the two
 * requests can be tied together.
 *
 * Deliberately keyed on delivery, not receipt: if the business email failed,
 * nothing is remembered, so a visitor who resubmits after seeing the error
 * state gets a real second attempt rather than a silent no-op.
 *
 * Honest caveat, same as the rate limiter in app/api/contact/route.ts: this
 * Map lives in one serverless instance's memory. It resets on a cold start and
 * is not shared between concurrent instances, so a double-submit routed to two
 * different instances can still get through. It removes the common case (the
 * impatient second click, which lands on a warm instance milliseconds later)
 * and nothing here is correctness-critical, because the worst outcome it
 * prevents is a duplicate email rather than a lost lead.
 */
const WINDOW_MS = 15 * 60 * 1000;
const MAX_ENTRIES = 2000;

const delivered = new Map<string, { reference: string; at: number }>();

/**
 * Identifies a submission by its content, not by a client-supplied id: a
 * token from the browser can be regenerated by a second page load, and the
 * point is to catch the same person sending the same thing twice.
 */
export function fingerprintLead(lead: Lead): string {
  const fields = Object.keys(lead.fields)
    .sort()
    .map((key) => `${key}=${(lead.fields[key] ?? "").trim()}`)
    .join(" ");
  return createHash("sha256")
    .update(`${lead.source} ${fields}`)
    .digest("hex")
    .slice(0, 32);
}

function prune(now: number): void {
  for (const [key, entry] of delivered) {
    if (now - entry.at >= WINDOW_MS) delivered.delete(key);
  }
  // Unbounded-growth guard for the pathological case where everything in the
  // map is still inside the window.
  if (delivered.size > MAX_ENTRIES) delivered.clear();
}

/** The reference this exact submission was already delivered under, if any. */
export function previousDelivery(fingerprint: string): string | undefined {
  const now = Date.now();
  prune(now);
  const entry = delivered.get(fingerprint);
  if (!entry) return undefined;
  return now - entry.at < WINDOW_MS ? entry.reference : undefined;
}

/** Called only after the BUSINESS email has actually been accepted. */
export function rememberDelivery(fingerprint: string, reference: string): void {
  const now = Date.now();
  prune(now);
  delivered.set(fingerprint, { reference, at: now });
}
