/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type FinalCta = {
  _type: "finalCta";
  heading?: string;
  body?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
};

export type RelatedServices = {
  _type: "relatedServices";
  heading?: string;
  serviceSlugs?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ServiceArea = {
  _type: "serviceArea";
  heading?: string;
  body?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoSubject?: string;
};

export type ServiceFaq = {
  _type: "serviceFaq";
  heading?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _type: "faq";
    _key: string;
  }>;
};

export type PropertyTypes = {
  _type: "propertyTypes";
  heading?: string;
  cards?: Array<{
    title?: string;
    blurb?: string;
    slug?: string;
    icon?: "building" | "hotel" | "heart-handshake" | "stethoscope";
    _type: "card";
    _key: string;
  }>;
};

export type ServiceTestimonials = {
  _type: "serviceTestimonials";
  heading?: string;
};

export type ServiceTrust = {
  _type: "serviceTrust";
  heading?: string;
  items?: Array<{
    title?: string;
    description?: string;
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    _type: "item";
    _key: string;
  }>;
  showLogos?: boolean;
};

export type ComparisonTable = {
  _type: "comparisonTable";
  heading?: string;
  rows?: Array<{
    situation?: string;
    recommendation?: string;
    why?: string;
    _type: "row";
    _key: string;
  }>;
  footnote?: string;
};

export type ProcessSteps = {
  _type: "processSteps";
  heading?: string;
  steps?: Array<{
    title?: string;
    description?: string;
    _type: "step";
    _key: string;
  }>;
};

export type SignsYouNeed = {
  _type: "signsYouNeed";
  heading?: string;
  cards?: Array<{
    question?: string;
    answer?: string;
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    _type: "card";
    _key: string;
  }>;
  ctaLabel?: string;
  ctaHref?: string;
};

export type WhatsIncluded = {
  _type: "whatsIncluded";
  heading?: string;
  intro?: string;
  items?: Array<{
    title?: string;
    description?: string;
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    href?: string;
    _type: "item";
    _key: string;
  }>;
};

export type ServiceAbout = {
  _type: "serviceAbout";
  heading?: string;
  paragraphs?: Array<string>;
  ctaLabel?: string;
  ctaHref?: string;
  photoPrimary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoSubjectPrimary?: string;
  photoSecondary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoSubjectSecondary?: string;
};

export type ServiceHero = {
  _type: "serviceHero";
  heading?: string;
  subheading?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  credentials?: Array<{
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    label?: string;
    _type: "credential";
    _key: string;
  }>;
  eyebrow?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoSubject?: string;
};

export type TrustLogo = {
  _id: string;
  _type: "trustLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  bulletPoints?: Array<string>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  >;
  slug?: Slug;
  seoTitle?: string;
  seoDescription?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shortDescription?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ServiceHero)
    | ({
        _key: string;
      } & ServiceAbout)
    | ({
        _key: string;
      } & WhatsIncluded)
    | ({
        _key: string;
      } & SignsYouNeed)
    | ({
        _key: string;
      } & ProcessSteps)
    | ({
        _key: string;
      } & ComparisonTable)
    | ({
        _key: string;
      } & ServiceTrust)
    | ({
        _key: string;
      } & ServiceTestimonials)
    | ({
        _key: string;
      } & PropertyTypes)
    | ({
        _key: string;
      } & ServiceFaq)
    | ({
        _key: string;
      } & ServiceArea)
    | ({
        _key: string;
      } & RelatedServices)
    | ({
        _key: string;
      } & FinalCta)
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  >;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  icon?:
    | "wrench"
    | "siren"
    | "waves"
    | "calendar-check"
    | "building-2"
    | "cog"
    | "shield-check"
    | "heart-pulse"
    | "graduation-cap";
  featured?: boolean;
  order?: number;
  slug?: Slug;
  seoTitle?: string;
  seoDescription?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  role?: string;
  date?: string;
  rating?: number;
  featured?: boolean;
  order?: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  order?: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    label?: string;
    href?: string;
    children?: Array<{
      label?: string;
      href?: string;
      description?: string;
      icon?:
        | "wrench"
        | "cog"
        | "siren"
        | "waves"
        | "calendar-check"
        | "building-2"
        | "heart-pulse"
        | "graduation-cap"
        | "building"
        | "hotel"
        | "heart-handshake"
        | "stethoscope"
        | "map-pin";
      _type: "navLink";
      _key: string;
    }>;
    layout?: "mega" | "list";
    showServiceAreaCities?: boolean;
    _type: "navGroup";
    _key: string;
  }>;
  cta?: {
    label?: string;
    href?: string;
  };
  footerColumns?: Array<{
    heading?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _type: "footerLink";
      _key: string;
    }>;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<{
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  legalName?: string;
  tagline?: string;
  phone?: string;
  phoneHref?: string;
  email?: string;
  emailHref?: string;
  serviceArea?: string;
  foundedYear?: number;
  yearsInBusiness?: string;
  url?: string;
  serviceAreaCities?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FinalCta
  | RelatedServices
  | SanityImageAssetReference
  | ServiceArea
  | ServiceFaq
  | PropertyTypes
  | ServiceTestimonials
  | ServiceTrust
  | ComparisonTable
  | ProcessSteps
  | SignsYouNeed
  | WhatsIncluded
  | ServiceAbout
  | ServiceHero
  | TrustLogo
  | SanityImageCrop
  | SanityImageHotspot
  | Industry
  | Slug
  | Service
  | Testimonial
  | Faq
  | Navigation
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    name,    legalName,    tagline,    phone,    phoneHref,    email,    emailHref,    serviceArea,    foundedYear,    yearsInBusiness,    url,    serviceAreaCities  }
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string | null;
  legalName: string | null;
  tagline: string | null;
  phone: string | null;
  phoneHref: string | null;
  email: string | null;
  emailHref: string | null;
  serviceArea: string | null;
  foundedYear: number | null;
  yearsInBusiness: string | null;
  url: string | null;
  serviceAreaCities: Array<string> | null;
} | null;

// Source: sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0]{    items[]{      _key,      label,      href,      layout,      showServiceAreaCities,      children[]{        _key,        label,        href,        description,        icon      }    },    cta{ label, href }  }
export type NAVIGATION_QUERY_RESULT = {
  items: Array<{
    _key: string;
    label: string | null;
    href: string | null;
    layout: "list" | "mega" | null;
    showServiceAreaCities: boolean | null;
    children: Array<{
      _key: string;
      label: string | null;
      href: string | null;
      description: string | null;
      icon:
        | "building-2"
        | "building"
        | "calendar-check"
        | "cog"
        | "graduation-cap"
        | "heart-handshake"
        | "heart-pulse"
        | "hotel"
        | "map-pin"
        | "siren"
        | "stethoscope"
        | "waves"
        | "wrench"
        | null;
    }> | null;
  }> | null;
  cta: {
    label: string | null;
    href: string | null;
  } | null;
} | null;

// Source: sanity/queries.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(order asc){ question, answer }
export type FAQS_QUERY_RESULT = Array<{
  question: string | null;
  answer: string | null;
}>;

// Source: sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc){    name, role, rating, quote, date, featured  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  name: string | null;
  role: string | null;
  rating: number | null;
  quote: string | null;
  date: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc){    title,    "slug": slug.current,    shortDescription,    icon,    featured,    photo{ asset, hotspot, crop, alt },    body,    seoTitle,    seoDescription  }
export type SERVICES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  icon:
    | "building-2"
    | "calendar-check"
    | "cog"
    | "graduation-cap"
    | "heart-pulse"
    | "shield-check"
    | "siren"
    | "waves"
    | "wrench"
    | null;
  featured: boolean | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
}>;

// Source: sanity/queries.ts
// Variable: SERVICE_BY_SLUG_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    title,    "slug": slug.current,    shortDescription,    icon,    featured,    photo{ asset, hotspot, crop, alt },    body,    sections[]{      ...,      photo{ asset, hotspot, crop, alt },      photoPrimary{ asset, hotspot, crop, alt },      photoSecondary{ asset, hotspot, crop, alt }    },    seoTitle,    seoDescription  }
export type SERVICE_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  icon:
    | "building-2"
    | "calendar-check"
    | "cog"
    | "graduation-cap"
    | "heart-pulse"
    | "shield-check"
    | "siren"
    | "waves"
    | "wrench"
    | null;
  featured: boolean | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  sections: Array<
    | {
        _key: string;
        _type: "comparisonTable";
        heading?: string;
        rows?: Array<{
          situation?: string;
          recommendation?: string;
          why?: string;
          _type: "row";
          _key: string;
        }>;
        footnote?: string;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "finalCta";
        heading?: string;
        body?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "processSteps";
        heading?: string;
        steps?: Array<{
          title?: string;
          description?: string;
          _type: "step";
          _key: string;
        }>;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "propertyTypes";
        heading?: string;
        cards?: Array<{
          title?: string;
          blurb?: string;
          slug?: string;
          icon?: "building" | "heart-handshake" | "hotel" | "stethoscope";
          _type: "card";
          _key: string;
        }>;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "relatedServices";
        heading?: string;
        serviceSlugs?: Array<string>;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "serviceAbout";
        heading?: string;
        paragraphs?: Array<string>;
        ctaLabel?: string;
        ctaHref?: string;
        photoPrimary: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubjectPrimary?: string;
        photoSecondary: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubjectSecondary?: string;
        photo: null;
      }
    | {
        _key: string;
        _type: "serviceArea";
        heading?: string;
        body?: string;
        photo: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubject?: string;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "serviceFaq";
        heading?: string;
        faqs?: Array<{
          question?: string;
          answer?: string;
          _type: "faq";
          _key: string;
        }>;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "serviceHero";
        heading?: string;
        subheading?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        credentials?: Array<{
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          label?: string;
          _type: "credential";
          _key: string;
        }>;
        eyebrow?: string;
        photo: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubject?: string;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "serviceTestimonials";
        heading?: string;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "serviceTrust";
        heading?: string;
        items?: Array<{
          title?: string;
          description?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          _type: "item";
          _key: string;
        }>;
        showLogos?: boolean;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "signsYouNeed";
        heading?: string;
        cards?: Array<{
          question?: string;
          answer?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          _type: "card";
          _key: string;
        }>;
        ctaLabel?: string;
        ctaHref?: string;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
    | {
        _key: string;
        _type: "whatsIncluded";
        heading?: string;
        intro?: string;
        items?: Array<{
          title?: string;
          description?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          href?: string;
          _type: "item";
          _key: string;
        }>;
        photo: null;
        photoPrimary: null;
        photoSecondary: null;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: INDUSTRIES_QUERY
// Query: *[_type == "industry"] | order(order asc){    title,    "slug": slug.current,    description,    bulletPoints,    photo{ asset, hotspot, crop, alt },    body,    seoTitle,    seoDescription  }
export type INDUSTRIES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  bulletPoints: Array<string> | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
}>;

// Source: sanity/queries.ts
// Variable: INDUSTRY_BY_SLUG_QUERY
// Query: *[_type == "industry" && slug.current == $slug][0]{    title,    "slug": slug.current,    description,    bulletPoints,    photo{ asset, hotspot, crop, alt },    body,    seoTitle,    seoDescription  }
export type INDUSTRY_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  description: string | null;
  bulletPoints: Array<string> | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: TRUST_LOGOS_QUERY
// Query: *[_type == "trustLogo"] | order(order asc){    name,    logo{ asset, hotspot, crop, alt }  }
export type TRUST_LOGOS_QUERY_RESULT = Array<{
  name: string | null;
  logo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
}>;

// Source: sanity/queries.ts
// Variable: FOOTER_NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0]{    footerColumns[]{      _key,      heading,      links[]{ _key, label, href }    },    legalLinks[]{ _key, label, href }  }
export type FOOTER_NAVIGATION_QUERY_RESULT = {
  footerColumns: Array<{
    _key: string;
    heading: string | null;
    links: Array<{
      _key: string;
      label: string | null;
      href: string | null;
    }> | null;
  }> | null;
  legalLinks: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{\n    name,\n    legalName,\n    tagline,\n    phone,\n    phoneHref,\n    email,\n    emailHref,\n    serviceArea,\n    foundedYear,\n    yearsInBusiness,\n    url,\n    serviceAreaCities\n  }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "navigation" && _id == "navigation"][0]{\n    items[]{\n      _key,\n      label,\n      href,\n      layout,\n      showServiceAreaCities,\n      children[]{\n        _key,\n        label,\n        href,\n        description,\n        icon\n      }\n    },\n    cta{ label, href }\n  }': NAVIGATION_QUERY_RESULT;
    '*[_type == "faq"] | order(order asc){ question, answer }': FAQS_QUERY_RESULT;
    '*[_type == "testimonial"] | order(order asc){\n    name, role, rating, quote, date, featured\n  }': TESTIMONIALS_QUERY_RESULT;
    '*[_type == "service"] | order(order asc){\n    title,\n    "slug": slug.current,\n    shortDescription,\n    icon,\n    featured,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    seoTitle,\n    seoDescription\n  }': SERVICES_QUERY_RESULT;
    '*[_type == "service" && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    shortDescription,\n    icon,\n    featured,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    sections[]{\n      ...,\n      photo{ asset, hotspot, crop, alt },\n      photoPrimary{ asset, hotspot, crop, alt },\n      photoSecondary{ asset, hotspot, crop, alt }\n    },\n    seoTitle,\n    seoDescription\n  }': SERVICE_BY_SLUG_QUERY_RESULT;
    '*[_type == "industry"] | order(order asc){\n    title,\n    "slug": slug.current,\n    description,\n    bulletPoints,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    seoTitle,\n    seoDescription\n  }': INDUSTRIES_QUERY_RESULT;
    '*[_type == "industry" && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    description,\n    bulletPoints,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    seoTitle,\n    seoDescription\n  }': INDUSTRY_BY_SLUG_QUERY_RESULT;
    '*[_type == "trustLogo"] | order(order asc){\n    name,\n    logo{ asset, hotspot, crop, alt }\n  }': TRUST_LOGOS_QUERY_RESULT;
    '*[_type == "navigation" && _id == "navigation"][0]{\n    footerColumns[]{\n      _key,\n      heading,\n      links[]{ _key, label, href }\n    },\n    legalLinks[]{ _key, label, href }\n  }': FOOTER_NAVIGATION_QUERY_RESULT;
  }
}
