/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Photo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "photo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type FinalCta = {
  _type: "finalCta";
  heading?: string;
  body?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  phoneCtaLabel?: string;
  showAvailabilityDot?: boolean;
};

export type RelatedServices = {
  _type: "relatedServices";
  heading?: string;
  serviceSlugs?: Array<string>;
};

export type ServiceArea = {
  _type: "serviceArea";
  heading?: string;
  body?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoSubject?: string;
};

export type ServiceFaq = {
  _type: "serviceFaq";
  heading?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    href?: string;
    linkLabel?: string;
    _type: "faq";
    _key: string;
  }>;
  background?: "offwhite" | "white";
};

export type PropertyTypes = {
  _type: "propertyTypes";
  heading?: string;
  cards?: Array<{
    title?: string;
    blurb?: string;
    slug?: string;
    icon?: "building" | "hotel" | "heart-handshake" | "stethoscope";
    photo?: Photo;
    photoSubject?: string;
    _type: "card";
    _key: string;
  }>;
  background?: "dark" | "white" | "offwhite";
  ctaLabel?: string;
  ctaHref?: string;
};

export type ServiceTestimonials = {
  _type: "serviceTestimonials";
  heading?: string;
  filterTags?: Array<string>;
  limit?: number;
};

export type ServiceTrust = {
  _type: "serviceTrust";
  heading?: string;
  items?: Array<{
    title?: string;
    description?: string;
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    _type: "item";
    _key: string;
  }>;
  showLogos?: boolean;
};

export type ComparisonTable = {
  _type: "comparisonTable";
  heading?: string;
  intro?: string;
  columnLabels?: Array<string>;
  rows?: Array<{
    situation?: string;
    recommendation?: string;
    why?: string;
    _type: "row";
    _key: string;
  }>;
  footnote?: string;
  background?: "white" | "dark";
};

export type ProcessSteps = {
  _type: "processSteps";
  heading?: string;
  steps?: Array<{
    title?: string;
    description?: string;
    _type: "step";
    _key: string;
  }>;
  background?: "dark" | "white";
};

export type SignsYouNeed = {
  _type: "signsYouNeed";
  heading?: string;
  cards?: Array<{
    question?: string;
    answer?: string;
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    _type: "card";
    _key: string;
  }>;
  ctaLabel?: string;
  ctaHref?: string;
  background?: "white" | "dark";
};

export type WhatsIncluded = {
  _type: "whatsIncluded";
  heading?: string;
  intro?: string;
  items?: Array<{
    title?: string;
    description?: string;
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    href?: string;
    _type: "item";
    _key: string;
  }>;
};

export type ServiceAbout = {
  _type: "serviceAbout";
  heading?: string;
  paragraphs?: Array<string>;
  ctaLabel?: string;
  ctaHref?: string;
  photoPrimary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoSubjectPrimary?: string;
};

export type ServiceHero = {
  _type: "serviceHero";
  heading?: string;
  subheading?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  credentials?: Array<{
    icon?:
      | "droplets"
      | "wrench"
      | "building-2"
      | "flame"
      | "shield-check"
      | "calendar-check"
      | "gauge"
      | "waves"
      | "siren"
      | "clock"
      | "award"
      | "cog"
      | "map-pin";
    label?: string;
    _type: "credential";
    _key: string;
  }>;
  eyebrow?: string;
  phoneCtaLabel?: string;
  showAvailabilityDot?: boolean;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoSubject?: string;
};

export type JobPosting = {
  _id: string;
  _type: "jobPosting";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  employmentType?: "FULL_TIME" | "PART_TIME" | "CONTRACTOR" | "TEMPORARY";
  team?: string;
  shift?: string;
  openings?: number;
  summary?: string;
  responsibilities?: Array<string>;
  requirements?: Array<string>;
  compensationNote?: string;
  applyEmail?: string;
  applyUrl?: string;
  datePosted?: string;
  validThrough?: string;
  open?: boolean;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TrustLogo = {
  _id: string;
  _type: "trustLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  headline?: string;
  blurb?: string;
  category?:
    "vendor-portal" | "compliance-network" | "association" | "credential";
  url?: string;
  verified?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  bulletPoints?: Array<string>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
  sections?: Array<
    | ({
        _key: string;
      } & ServiceHero)
    | ({
        _key: string;
      } & ServiceAbout)
    | ({
        _key: string;
      } & WhatsIncluded)
    | ({
        _key: string;
      } & SignsYouNeed)
    | ({
        _key: string;
      } & ProcessSteps)
    | ({
        _key: string;
      } & ComparisonTable)
    | ({
        _key: string;
      } & ServiceTrust)
    | ({
        _key: string;
      } & ServiceTestimonials)
    | ({
        _key: string;
      } & PropertyTypes)
    | ({
        _key: string;
      } & ServiceFaq)
    | ({
        _key: string;
      } & ServiceArea)
    | ({
        _key: string;
      } & RelatedServices)
    | ({
        _key: string;
      } & FinalCta)
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  >;
  slug?: Slug;
  seoTitle?: string;
  seoDescription?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shortDescription?: string;
  sections?: Array<
    | ({
        _key: string;
      } & ServiceHero)
    | ({
        _key: string;
      } & ServiceAbout)
    | ({
        _key: string;
      } & WhatsIncluded)
    | ({
        _key: string;
      } & SignsYouNeed)
    | ({
        _key: string;
      } & ProcessSteps)
    | ({
        _key: string;
      } & ComparisonTable)
    | ({
        _key: string;
      } & ServiceTrust)
    | ({
        _key: string;
      } & ServiceTestimonials)
    | ({
        _key: string;
      } & PropertyTypes)
    | ({
        _key: string;
      } & ServiceFaq)
    | ({
        _key: string;
      } & ServiceArea)
    | ({
        _key: string;
      } & RelatedServices)
    | ({
        _key: string;
      } & FinalCta)
  >;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  >;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  icon?:
    | "wrench"
    | "siren"
    | "waves"
    | "calendar-check"
    | "building-2"
    | "cog"
    | "shield-check"
    | "heart-pulse"
    | "graduation-cap";
  featured?: boolean;
  order?: number;
  slug?: Slug;
  seoTitle?: string;
  seoDescription?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  role?: string;
  date?: string;
  rating?: number;
  source?: "google" | "direct";
  reviewerMeta?: string;
  sourceUrl?: string;
  serviceTags?: Array<string>;
  ownerReply?: string;
  ownerReplyDate?: string;
  verified?: boolean;
  featured?: boolean;
  order?: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  order?: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    label?: string;
    href?: string;
    children?: Array<{
      label?: string;
      href?: string;
      description?: string;
      icon?:
        | "wrench"
        | "cog"
        | "siren"
        | "waves"
        | "calendar-check"
        | "building-2"
        | "heart-pulse"
        | "graduation-cap"
        | "building"
        | "hotel"
        | "heart-handshake"
        | "stethoscope"
        | "map-pin";
      _type: "navLink";
      _key: string;
    }>;
    layout?: "mega" | "list";
    showServiceAreaCities?: boolean;
    _type: "navGroup";
    _key: string;
  }>;
  cta?: {
    label?: string;
    href?: string;
  };
  footerColumns?: Array<{
    heading?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _type: "footerLink";
      _key: string;
    }>;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<{
    label?: string;
    href?: string;
    _type: "footerLink";
    _key: string;
  }>;
};

export type ReviewSettings = {
  _id: string;
  _type: "reviewSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  rating?: number;
  reviewCount?: number;
  verifiedOn?: string;
  reviewsUrl?: string;
  writeReviewUrl?: string;
  headline?: string;
};

export type CityPage = {
  _id: string;
  _type: "cityPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  city?: string;
  slug?: Slug;
  heroHeading?: string;
  heroIntro?: string;
  servicesHeading?: string;
  serviceCards?: Array<{
    title?: string;
    description?: string;
    href?: string;
    icon?:
      | "wrench"
      | "waves"
      | "cog"
      | "calendar-check"
      | "siren"
      | "building-2"
      | "shield-check";
    _type: "card";
    _key: string;
  }>;
  whyChooseHeading?: string;
  whyChooseBody?: string;
  reviewsHeading?: string;
  heritageHeading?: string;
  heritageParagraphs?: Array<string>;
  heritagePhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heritagePhotoSubject?: string;
  communitiesHeading?: string;
  communitiesBody?: string;
  communities?: Array<string>;
  showLogoStrip?: boolean;
  seoTitle?: string;
  seoDescription?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroIntro?: string;
  responsePromise?: string;
  hours?: Array<{
    days?: string;
    hours?: string;
    _type: "row";
    _key: string;
  }>;
  emergencyHeading?: string;
  emergencyBody?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _type: "faq";
    _key: string;
  }>;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroParagraphs?: Array<string>;
  storyHeading?: string;
  storyParagraphs?: Array<string>;
  storyPhotoPrimary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  storyPhotoSubjectPrimary?: string;
  storyPhotoSecondary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  storyPhotoSubjectSecondary?: string;
  evolutionHeading?: string;
  evolutionParagraphs?: Array<string>;
  evolutionPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  evolutionPhotoSubject?: string;
  valuesHeading?: string;
  values?: Array<{
    icon?:
      | "award"
      | "shield-check"
      | "clock"
      | "siren"
      | "wrench"
      | "building-2"
      | "heart-handshake";
    title?: string;
    description?: string;
    _type: "value";
    _key: string;
  }>;
  linksHeading?: string;
  links?: Array<{
    title?: string;
    description?: string;
    href?: string;
    _type: "link";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  legalName?: string;
  tagline?: string;
  phone?: string;
  phoneHref?: string;
  email?: string;
  emailHref?: string;
  serviceArea?: string;
  foundedYear?: number;
  yearsInBusiness?: string;
  licenseNumber?: string;
  url?: string;
  streetAddress?: string;
  addressLocality?: string;
  addressRegion?: string;
  postalCode?: string;
  serviceAreaCities?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Photo
  | FinalCta
  | RelatedServices
  | ServiceArea
  | ServiceFaq
  | PropertyTypes
  | ServiceTestimonials
  | ServiceTrust
  | ComparisonTable
  | ProcessSteps
  | SignsYouNeed
  | WhatsIncluded
  | ServiceAbout
  | ServiceHero
  | JobPosting
  | Slug
  | TrustLogo
  | SanityImageCrop
  | SanityImageHotspot
  | Industry
  | Service
  | Testimonial
  | Faq
  | Navigation
  | ReviewSettings
  | CityPage
  | ContactPage
  | AboutPage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    name,    legalName,    tagline,    phone,    phoneHref,    email,    emailHref,    serviceArea,    foundedYear,    yearsInBusiness,    url,    licenseNumber,    streetAddress,    addressLocality,    addressRegion,    postalCode,    serviceAreaCities  }
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string | null;
  legalName: string | null;
  tagline: string | null;
  phone: string | null;
  phoneHref: string | null;
  email: string | null;
  emailHref: string | null;
  serviceArea: string | null;
  foundedYear: number | null;
  yearsInBusiness: string | null;
  url: string | null;
  licenseNumber: string | null;
  streetAddress: string | null;
  addressLocality: string | null;
  addressRegion: string | null;
  postalCode: string | null;
  serviceAreaCities: Array<string> | null;
} | null;

// Source: sanity/queries.ts
// Variable: JOB_POSTINGS_QUERY
// Query: *[_type == "jobPosting" && open == true] | order(order asc){  title,  "slug": slug.current,  employmentType,  team,  shift,  openings,  summary,  responsibilities,  requirements,  compensationNote,  applyEmail,  applyUrl,  datePosted,  validThrough,  open}
export type JOB_POSTINGS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  employmentType: "CONTRACTOR" | "FULL_TIME" | "PART_TIME" | "TEMPORARY" | null;
  team: string | null;
  shift: string | null;
  openings: number | null;
  summary: string | null;
  responsibilities: Array<string> | null;
  requirements: Array<string> | null;
  compensationNote: string | null;
  applyEmail: string | null;
  applyUrl: string | null;
  datePosted: string | null;
  validThrough: string | null;
  open: true;
}>;

// Source: sanity/queries.ts
// Variable: JOB_POSTING_QUERY
// Query: *[_type == "jobPosting" && slug.current == $slug][0]{  title,  "slug": slug.current,  employmentType,  team,  shift,  openings,  summary,  responsibilities,  requirements,  compensationNote,  applyEmail,  applyUrl,  datePosted,  validThrough,  open}
export type JOB_POSTING_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  employmentType: "CONTRACTOR" | "FULL_TIME" | "PART_TIME" | "TEMPORARY" | null;
  team: string | null;
  shift: string | null;
  openings: number | null;
  summary: string | null;
  responsibilities: Array<string> | null;
  requirements: Array<string> | null;
  compensationNote: string | null;
  applyEmail: string | null;
  applyUrl: string | null;
  datePosted: string | null;
  validThrough: string | null;
  open: boolean | null;
} | null;

// Source: sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0]{    items[]{      _key,      label,      href,      layout,      showServiceAreaCities,      children[]{        _key,        label,        href,        description,        icon      }    },    cta{ label, href }  }
export type NAVIGATION_QUERY_RESULT = {
  items: Array<{
    _key: string;
    label: string | null;
    href: string | null;
    layout: "list" | "mega" | null;
    showServiceAreaCities: boolean | null;
    children: Array<{
      _key: string;
      label: string | null;
      href: string | null;
      description: string | null;
      icon:
        | "building-2"
        | "building"
        | "calendar-check"
        | "cog"
        | "graduation-cap"
        | "heart-handshake"
        | "heart-pulse"
        | "hotel"
        | "map-pin"
        | "siren"
        | "stethoscope"
        | "waves"
        | "wrench"
        | null;
    }> | null;
  }> | null;
  cta: {
    label: string | null;
    href: string | null;
  } | null;
} | null;

// Source: sanity/queries.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(order asc){ question, answer }
export type FAQS_QUERY_RESULT = Array<{
  question: string | null;
  answer: string | null;
}>;

// Source: sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc){    "id": _id, name, role, rating, quote, date, featured,    source, reviewerMeta, sourceUrl, serviceTags, verified,    ownerReply, ownerReplyDate  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  id: string;
  name: string | null;
  role: string | null;
  rating: number | null;
  quote: string | null;
  date: string | null;
  featured: boolean | null;
  source: "direct" | "google" | null;
  reviewerMeta: string | null;
  sourceUrl: string | null;
  serviceTags: Array<string> | null;
  verified: boolean | null;
  ownerReply: string | null;
  ownerReplyDate: string | null;
}>;

// Source: sanity/queries.ts
// Variable: REVIEW_SETTINGS_QUERY
// Query: *[_type == "reviewSettings" && _id == "reviewSettings"][0]{    rating,    reviewCount,    verifiedOn,    reviewsUrl,    writeReviewUrl,    headline  }
export type REVIEW_SETTINGS_QUERY_RESULT = {
  rating: number | null;
  reviewCount: number | null;
  verifiedOn: string | null;
  reviewsUrl: string | null;
  writeReviewUrl: string | null;
  headline: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc){    title,    "slug": slug.current,    shortDescription,    icon,    featured,    photo{ asset, hotspot, crop, alt },    body,    seoTitle,    seoDescription  }
export type SERVICES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  icon:
    | "building-2"
    | "calendar-check"
    | "cog"
    | "graduation-cap"
    | "heart-pulse"
    | "shield-check"
    | "siren"
    | "waves"
    | "wrench"
    | null;
  featured: boolean | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
}>;

// Source: sanity/queries.ts
// Variable: SERVICE_BY_SLUG_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    title,    "slug": slug.current,    shortDescription,    icon,    featured,    photo{ asset, hotspot, crop, alt },    body,    sections[]{      ...,      photo{ asset, hotspot, crop, alt },      photoPrimary{ asset, hotspot, crop, alt }    },    seoTitle,    seoDescription  }
export type SERVICE_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  shortDescription: string | null;
  icon:
    | "building-2"
    | "calendar-check"
    | "cog"
    | "graduation-cap"
    | "heart-pulse"
    | "shield-check"
    | "siren"
    | "waves"
    | "wrench"
    | null;
  featured: boolean | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  sections: Array<
    | {
        _key: string;
        _type: "comparisonTable";
        heading?: string;
        intro?: string;
        columnLabels?: Array<string>;
        rows?: Array<{
          situation?: string;
          recommendation?: string;
          why?: string;
          _type: "row";
          _key: string;
        }>;
        footnote?: string;
        background?: "dark" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "finalCta";
        heading?: string;
        body?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        phoneCtaLabel?: string;
        showAvailabilityDot?: boolean;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "processSteps";
        heading?: string;
        steps?: Array<{
          title?: string;
          description?: string;
          _type: "step";
          _key: string;
        }>;
        background?: "dark" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "propertyTypes";
        heading?: string;
        cards?: Array<{
          title?: string;
          blurb?: string;
          slug?: string;
          icon?: "building" | "heart-handshake" | "hotel" | "stethoscope";
          photo?: Photo;
          photoSubject?: string;
          _type: "card";
          _key: string;
        }>;
        background?: "dark" | "offwhite" | "white";
        ctaLabel?: string;
        ctaHref?: string;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "relatedServices";
        heading?: string;
        serviceSlugs?: Array<string>;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceAbout";
        heading?: string;
        paragraphs?: Array<string>;
        ctaLabel?: string;
        ctaHref?: string;
        photoPrimary: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubjectPrimary?: string;
        photo: null;
      }
    | {
        _key: string;
        _type: "serviceArea";
        heading?: string;
        body?: string;
        photo: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubject?: string;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceFaq";
        heading?: string;
        faqs?: Array<{
          question?: string;
          answer?: string;
          href?: string;
          linkLabel?: string;
          _type: "faq";
          _key: string;
        }>;
        background?: "offwhite" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceHero";
        heading?: string;
        subheading?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        credentials?: Array<{
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          label?: string;
          _type: "credential";
          _key: string;
        }>;
        eyebrow?: string;
        phoneCtaLabel?: string;
        showAvailabilityDot?: boolean;
        photo: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubject?: string;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceTestimonials";
        heading?: string;
        filterTags?: Array<string>;
        limit?: number;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceTrust";
        heading?: string;
        items?: Array<{
          title?: string;
          description?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          _type: "item";
          _key: string;
        }>;
        showLogos?: boolean;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "signsYouNeed";
        heading?: string;
        cards?: Array<{
          question?: string;
          answer?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          _type: "card";
          _key: string;
        }>;
        ctaLabel?: string;
        ctaHref?: string;
        background?: "dark" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "whatsIncluded";
        heading?: string;
        intro?: string;
        items?: Array<{
          title?: string;
          description?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          href?: string;
          _type: "item";
          _key: string;
        }>;
        photo: null;
        photoPrimary: null;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: INDUSTRIES_QUERY
// Query: *[_type == "industry"] | order(order asc){    title,    "slug": slug.current,    description,    bulletPoints,    photo{ asset, hotspot, crop, alt },    body,    seoTitle,    seoDescription  }
export type INDUSTRIES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  bulletPoints: Array<string> | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
}>;

// Source: sanity/queries.ts
// Variable: INDUSTRY_BY_SLUG_QUERY
// Query: *[_type == "industry" && slug.current == $slug][0]{    title,    "slug": slug.current,    description,    bulletPoints,    photo{ asset, hotspot, crop, alt },    body,    sections[]{      ...,      photo{ asset, hotspot, crop, alt },      photoPrimary{ asset, hotspot, crop, alt }    },    seoTitle,    seoDescription  }
export type INDUSTRY_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  description: string | null;
  bulletPoints: Array<string> | null;
  photo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        heading?: string;
        text?: string;
        showPhoneButton?: boolean;
        _type: "callout";
        _key: string;
      }
  > | null;
  sections: Array<
    | {
        _key: string;
        _type: "comparisonTable";
        heading?: string;
        intro?: string;
        columnLabels?: Array<string>;
        rows?: Array<{
          situation?: string;
          recommendation?: string;
          why?: string;
          _type: "row";
          _key: string;
        }>;
        footnote?: string;
        background?: "dark" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "finalCta";
        heading?: string;
        body?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        phoneCtaLabel?: string;
        showAvailabilityDot?: boolean;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "processSteps";
        heading?: string;
        steps?: Array<{
          title?: string;
          description?: string;
          _type: "step";
          _key: string;
        }>;
        background?: "dark" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "propertyTypes";
        heading?: string;
        cards?: Array<{
          title?: string;
          blurb?: string;
          slug?: string;
          icon?: "building" | "heart-handshake" | "hotel" | "stethoscope";
          photo?: Photo;
          photoSubject?: string;
          _type: "card";
          _key: string;
        }>;
        background?: "dark" | "offwhite" | "white";
        ctaLabel?: string;
        ctaHref?: string;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "relatedServices";
        heading?: string;
        serviceSlugs?: Array<string>;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceAbout";
        heading?: string;
        paragraphs?: Array<string>;
        ctaLabel?: string;
        ctaHref?: string;
        photoPrimary: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubjectPrimary?: string;
        photo: null;
      }
    | {
        _key: string;
        _type: "serviceArea";
        heading?: string;
        body?: string;
        photo: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubject?: string;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceFaq";
        heading?: string;
        faqs?: Array<{
          question?: string;
          answer?: string;
          href?: string;
          linkLabel?: string;
          _type: "faq";
          _key: string;
        }>;
        background?: "offwhite" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceHero";
        heading?: string;
        subheading?: string;
        secondaryCtaLabel?: string;
        secondaryCtaHref?: string;
        credentials?: Array<{
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          label?: string;
          _type: "credential";
          _key: string;
        }>;
        eyebrow?: string;
        phoneCtaLabel?: string;
        showAvailabilityDot?: boolean;
        photo: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
        } | null;
        photoSubject?: string;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceTestimonials";
        heading?: string;
        filterTags?: Array<string>;
        limit?: number;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "serviceTrust";
        heading?: string;
        items?: Array<{
          title?: string;
          description?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          _type: "item";
          _key: string;
        }>;
        showLogos?: boolean;
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "signsYouNeed";
        heading?: string;
        cards?: Array<{
          question?: string;
          answer?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          _type: "card";
          _key: string;
        }>;
        ctaLabel?: string;
        ctaHref?: string;
        background?: "dark" | "white";
        photo: null;
        photoPrimary: null;
      }
    | {
        _key: string;
        _type: "whatsIncluded";
        heading?: string;
        intro?: string;
        items?: Array<{
          title?: string;
          description?: string;
          icon?:
            | "award"
            | "building-2"
            | "calendar-check"
            | "clock"
            | "cog"
            | "droplets"
            | "flame"
            | "gauge"
            | "map-pin"
            | "shield-check"
            | "siren"
            | "waves"
            | "wrench";
          href?: string;
          _type: "item";
          _key: string;
        }>;
        photo: null;
        photoPrimary: null;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: TRUST_LOGOS_QUERY
// Query: *[_type == "trustLogo"] | order(order asc){    name,    logo{ asset, hotspot, crop, alt },    headline,    blurb,    category,    url,    verified  }
export type TRUST_LOGOS_QUERY_RESULT = Array<{
  name: string | null;
  logo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  headline: string | null;
  blurb: string | null;
  category:
    | "association"
    | "compliance-network"
    | "credential"
    | "vendor-portal"
    | null;
  url: string | null;
  verified: boolean | null;
}>;

// Source: sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    heroEyebrow,    heroHeading,    heroParagraphs,    storyHeading,    storyParagraphs,    storyPhotoPrimary{ asset, hotspot, crop, alt },    storyPhotoSubjectPrimary,    storyPhotoSecondary{ asset, hotspot, crop, alt },    storyPhotoSubjectSecondary,    evolutionHeading,    evolutionParagraphs,    evolutionPhoto{ asset, hotspot, crop, alt },    evolutionPhotoSubject,    valuesHeading,    values[]{ icon, title, description },    linksHeading,    links[]{ title, description, href }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroParagraphs: Array<string> | null;
  storyHeading: string | null;
  storyParagraphs: Array<string> | null;
  storyPhotoPrimary: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  storyPhotoSubjectPrimary: string | null;
  storyPhotoSecondary: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  storyPhotoSubjectSecondary: string | null;
  evolutionHeading: string | null;
  evolutionParagraphs: Array<string> | null;
  evolutionPhoto: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  evolutionPhotoSubject: string | null;
  valuesHeading: string | null;
  values: Array<{
    icon:
      | "award"
      | "building-2"
      | "clock"
      | "heart-handshake"
      | "shield-check"
      | "siren"
      | "wrench"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
  linksHeading: string | null;
  links: Array<{
    title: string | null;
    description: string | null;
    href: string | null;
  }> | null;
} | null;

// Source: sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{    heroEyebrow,    heroHeading,    heroIntro,    responsePromise,    hours[]{ days, hours },    emergencyHeading,    emergencyBody,    faqs[]{ question, answer }  }
export type CONTACT_PAGE_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroIntro: string | null;
  responsePromise: string | null;
  hours: Array<{
    days: string | null;
    hours: string | null;
  }> | null;
  emergencyHeading: string | null;
  emergencyBody: string | null;
  faqs: Array<{
    question: string | null;
    answer: string | null;
  }> | null;
} | null;

// Source: sanity/queries.ts
// Variable: CITY_PAGE_QUERY
// Query: *[_type == "cityPage" && slug.current == $slug][0]{    city,    "slug": slug.current,    heroHeading,    heroIntro,    servicesHeading,    serviceCards[]{ _key, title, description, href, icon },    whyChooseHeading,    whyChooseBody,    reviewsHeading,    heritageHeading,    heritageParagraphs,    heritagePhoto{ asset, hotspot, crop, alt },    heritagePhotoSubject,    communitiesHeading,    communitiesBody,    communities,    showLogoStrip,    seoTitle,    seoDescription  }
export type CITY_PAGE_QUERY_RESULT = {
  city: string | null;
  slug: string | null;
  heroHeading: string | null;
  heroIntro: string | null;
  servicesHeading: string | null;
  serviceCards: Array<{
    _key: string;
    title: string | null;
    description: string | null;
    href: string | null;
    icon:
      | "building-2"
      | "calendar-check"
      | "cog"
      | "shield-check"
      | "siren"
      | "waves"
      | "wrench"
      | null;
  }> | null;
  whyChooseHeading: string | null;
  whyChooseBody: string | null;
  reviewsHeading: string | null;
  heritageHeading: string | null;
  heritageParagraphs: Array<string> | null;
  heritagePhoto: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  heritagePhotoSubject: string | null;
  communitiesHeading: string | null;
  communitiesBody: string | null;
  communities: Array<string> | null;
  showLogoStrip: boolean | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: FOOTER_NAVIGATION_QUERY
// Query: *[_type == "navigation" && _id == "navigation"][0]{    footerColumns[]{      _key,      heading,      links[]{ _key, label, href }    },    legalLinks[]{ _key, label, href }  }
export type FOOTER_NAVIGATION_QUERY_RESULT = {
  footerColumns: Array<{
    _key: string;
    heading: string | null;
    links: Array<{
      _key: string;
      label: string | null;
      href: string | null;
    }> | null;
  }> | null;
  legalLinks: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{\n    name,\n    legalName,\n    tagline,\n    phone,\n    phoneHref,\n    email,\n    emailHref,\n    serviceArea,\n    foundedYear,\n    yearsInBusiness,\n    url,\n    licenseNumber,\n    streetAddress,\n    addressLocality,\n    addressRegion,\n    postalCode,\n    serviceAreaCities\n  }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "jobPosting" && open == true] | order(order asc){\n  title,\n  "slug": slug.current,\n  employmentType,\n  team,\n  shift,\n  openings,\n  summary,\n  responsibilities,\n  requirements,\n  compensationNote,\n  applyEmail,\n  applyUrl,\n  datePosted,\n  validThrough,\n  open\n}': JOB_POSTINGS_QUERY_RESULT;
    '*[_type == "jobPosting" && slug.current == $slug][0]{\n  title,\n  "slug": slug.current,\n  employmentType,\n  team,\n  shift,\n  openings,\n  summary,\n  responsibilities,\n  requirements,\n  compensationNote,\n  applyEmail,\n  applyUrl,\n  datePosted,\n  validThrough,\n  open\n}': JOB_POSTING_QUERY_RESULT;
    '*[_type == "navigation" && _id == "navigation"][0]{\n    items[]{\n      _key,\n      label,\n      href,\n      layout,\n      showServiceAreaCities,\n      children[]{\n        _key,\n        label,\n        href,\n        description,\n        icon\n      }\n    },\n    cta{ label, href }\n  }': NAVIGATION_QUERY_RESULT;
    '*[_type == "faq"] | order(order asc){ question, answer }': FAQS_QUERY_RESULT;
    '*[_type == "testimonial"] | order(order asc){\n    "id": _id, name, role, rating, quote, date, featured,\n    source, reviewerMeta, sourceUrl, serviceTags, verified,\n    ownerReply, ownerReplyDate\n  }': TESTIMONIALS_QUERY_RESULT;
    '*[_type == "reviewSettings" && _id == "reviewSettings"][0]{\n    rating,\n    reviewCount,\n    verifiedOn,\n    reviewsUrl,\n    writeReviewUrl,\n    headline\n  }': REVIEW_SETTINGS_QUERY_RESULT;
    '*[_type == "service"] | order(order asc){\n    title,\n    "slug": slug.current,\n    shortDescription,\n    icon,\n    featured,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    seoTitle,\n    seoDescription\n  }': SERVICES_QUERY_RESULT;
    '*[_type == "service" && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    shortDescription,\n    icon,\n    featured,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    sections[]{\n      ...,\n      photo{ asset, hotspot, crop, alt },\n      photoPrimary{ asset, hotspot, crop, alt }\n    },\n    seoTitle,\n    seoDescription\n  }': SERVICE_BY_SLUG_QUERY_RESULT;
    '*[_type == "industry"] | order(order asc){\n    title,\n    "slug": slug.current,\n    description,\n    bulletPoints,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    seoTitle,\n    seoDescription\n  }': INDUSTRIES_QUERY_RESULT;
    '*[_type == "industry" && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    description,\n    bulletPoints,\n    photo{ asset, hotspot, crop, alt },\n    body,\n    sections[]{\n      ...,\n      photo{ asset, hotspot, crop, alt },\n      photoPrimary{ asset, hotspot, crop, alt }\n    },\n    seoTitle,\n    seoDescription\n  }': INDUSTRY_BY_SLUG_QUERY_RESULT;
    '*[_type == "trustLogo"] | order(order asc){\n    name,\n    logo{ asset, hotspot, crop, alt },\n    headline,\n    blurb,\n    category,\n    url,\n    verified\n  }': TRUST_LOGOS_QUERY_RESULT;
    '*[_type == "aboutPage" && _id == "aboutPage"][0]{\n    heroEyebrow,\n    heroHeading,\n    heroParagraphs,\n    storyHeading,\n    storyParagraphs,\n    storyPhotoPrimary{ asset, hotspot, crop, alt },\n    storyPhotoSubjectPrimary,\n    storyPhotoSecondary{ asset, hotspot, crop, alt },\n    storyPhotoSubjectSecondary,\n    evolutionHeading,\n    evolutionParagraphs,\n    evolutionPhoto{ asset, hotspot, crop, alt },\n    evolutionPhotoSubject,\n    valuesHeading,\n    values[]{ icon, title, description },\n    linksHeading,\n    links[]{ title, description, href }\n  }': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "contactPage" && _id == "contactPage"][0]{\n    heroEyebrow,\n    heroHeading,\n    heroIntro,\n    responsePromise,\n    hours[]{ days, hours },\n    emergencyHeading,\n    emergencyBody,\n    faqs[]{ question, answer }\n  }': CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "cityPage" && slug.current == $slug][0]{\n    city,\n    "slug": slug.current,\n    heroHeading,\n    heroIntro,\n    servicesHeading,\n    serviceCards[]{ _key, title, description, href, icon },\n    whyChooseHeading,\n    whyChooseBody,\n    reviewsHeading,\n    heritageHeading,\n    heritageParagraphs,\n    heritagePhoto{ asset, hotspot, crop, alt },\n    heritagePhotoSubject,\n    communitiesHeading,\n    communitiesBody,\n    communities,\n    showLogoStrip,\n    seoTitle,\n    seoDescription\n  }': CITY_PAGE_QUERY_RESULT;
    '*[_type == "navigation" && _id == "navigation"][0]{\n    footerColumns[]{\n      _key,\n      heading,\n      links[]{ _key, label, href }\n    },\n    legalLinks[]{ _key, label, href }\n  }': FOOTER_NAVIGATION_QUERY_RESULT;
  }
}
