import {
  AlertTriangle,
  Award,
  Building,
  Building2,
  CalendarCheck,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock4,
  Cog,
  Droplets,
  FileCheck2,
  Flame,
  Gauge,
  Lightbulb,
  MessageSquare,
  PhoneCall,
  SearchCheck,
  ShieldCheck,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Hotel,
  MapPin,
  Siren,
  Stethoscope,
  TrendingUp,
  Truck,
  Waves,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { NavIconName } from "@/data/navigation";

/**
 * Resolves the string icon tokens carried by the navigation data (which must
 * stay serializable across the Server→Client boundary) to lucide components.
 */
export const navIcons: Record<NavIconName, LucideIcon> = {
  "shield-check": ShieldCheck,
  wrench: Wrench,
  cog: Cog,
  siren: Siren,
  waves: Waves,
  "calendar-check": CalendarCheck,
  "building-2": Building2,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  building: Building,
  hotel: Hotel,
  "heart-handshake": HeartHandshake,
  stethoscope: Stethoscope,
  "map-pin": MapPin,
  clock: Clock,
  "clock-4": Clock4,
  droplets: Droplets,
  flame: Flame,
  gauge: Gauge,
  award: Award,
  truck: Truck,
  "message-square": MessageSquare,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "phone-call": PhoneCall,
  "search-check": SearchCheck,
  "file-check-2": FileCheck2,
  "alert-triangle": AlertTriangle,
  lightbulb: Lightbulb,
  "trending-up": TrendingUp,
};
